### ISSUE TITLE
Killing the test suite can leave orphan tmux session

### ISSUE THREAD

**Issue by frasertweedale** [purebred-mua/tasty-tmux#13]
**Describe the bug**

If you kill the test suite with `^C`, the current tmux session remains.  A subsequent execution of the test suite encounters a duplicate session error.

**To Reproduce**

1. Run the test suite.
2. Kill the session at some point via `^C`.
3. Run the test suite again.  With high probability, a duplicate session error is encountered.

**Expected behavior**

Test sessions get cleaned up even when the test suite was interrupted.

Alternatively, orphan tmux sessions are detected and killed such that their existence does not cause a problem.

**Comment by romanofski** [comment]
Oh see... I think #15 must have been a duplicate :/ Close?

**Comment by frasertweedale** [comment]
Does the PR solve this too, i.e. the test session is killed by user at an arbitrary point?

**Comment by romanofski** [comment]
Yep. Just ran the acceptance tests and kill them as described in (2.).
